name: Build 11-garden and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 11-garden repository
      uses: actions/checkout@v3
      with:
        repository: binnyva/11-garden
        path: 11-garden

    - name: Edit siteConfig.js
      run: |
        echo "module.exports = {
          title: 'Digital Zen Garden',
          description: 'My Digital Garden, my Zettelkasten notes, a place to holds my thoughts...',
          url: 'https://notes.binnyva.com/',
          author: 'Binny V A',
          pathPrefix: '/',
          homeNote: 'Readme',
          headerMenu: [
            {type: 'page', item: '', title: 'Home'},
            {
              type: 'page', item: 'tags', title: 'Tags',
              menu: [
                {type: 'tag',item: 'zettelkasten'},
                {type: 'tag',item: 'psychology'},
                {type: 'tag',item: 'framework'},
                {type: 'tag',item: 'productivity'},
                {type: 'tag',item: 'philosophy'},
              ]
            },
          ],
        };" > 11-garden/_data/siteConfig.js

    - name: Edit index.njk
      run: |
        echo '---
        layout: base.njk
        type: index
        eleventyExcludeFromCollections: true
        ---

        <div class="column is-half">
          <h3>Hi there!</h3>

          {% if collections.homeNote.length == 1 %}
            <div class="note-content">
            {{ collections.homeNote[0].content | safe }}
            </div>
          {% endif %}

          <hr >

          <div class="block">
            <div id="search"></div>
            <script>
              window.addEventListener("DOMContentLoaded", (event) => {
                  new PagefindUI({ element: "#search", showSubResults: true, showImages: false });
              });
            </script>
          </div>

          <div class="block note-list note-cards">
            {% for note in collections.latestFiveNotes %}
              {% include "note-list-item.njk" %}
            {% endfor %}

            <a href="{{ "/sitemap/" | absoluteUrl }}">All Notes...</a>
          </div>

        </div>' > 11-garden/index.njk

    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        path: notes-repo

    - name: Copy notes
      run: |
        find '11-garden/_notes/' -type f -not -name _notes.11tydata.js -delete 
        cp -p notes-repo/Literature/*.* '11-garden/_notes'
        cp -p notes-repo/*.* '11-garden/_notes'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies and build
      working-directory: 11-garden
      run: |
        npm install
        npm run build

    - name: Deploy to remote server
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzc --delete
        path: 11-garden/_site/
        remote_path: ${{ secrets.BINNYVA_COM_NOTES_PATH }}
        remote_host: binnyva.com
        remote_user: ${{ secrets.BINNYVA_COM_USER }}
        remote_key: ${{ secrets.BINNYVA_COM_SSH_PRIVATE_KEY }}
